### ISSUE TITLE
Issue with User field

### ISSUE THREAD

**Issue by PedroTiagoSimao** [fleiflei/acf-admin-columns#11]
Hi flei!

Thank you so much for keeping this plugin active!
I've an issue when using a User type field, the content doesn't show in the admin column.
Is this any issue you have knowledge of?

<img width="674" alt="Screenshot 2023-11-17 at 11 29 29" src="https://github.com/fleiflei/acf-admin-columns/assets/5888256/a2d6946e-b467-431e-bd13-f7d76c1b0cab">

<img width="1033" alt="Screenshot 2023-11-17 at 11 32 25" src="https://github.com/fleiflei/acf-admin-columns/assets/5888256/65b0ca0d-a582-46ca-a2d7-99d51fa064ac">

<img width="804" alt="Screenshot 2023-11-17 at 11 30 06" src="https://github.com/fleiflei/acf-admin-columns/assets/5888256/fab03a17-4494-4eef-96a7-803f836f0160">

**Comment by fleiflei** [comment]
Hello @PedroTiagoSimao ,

thank you for pointing this error out...I have just fixed it..please try if it works correctly with the latest v0.3.1...

If you like this plugin your star rating here on Github or your review on https://wordpress.org/plugins/admin-columns-for-acf-fields/#reviews are greatly appreciated!

Best regards,
Florian

**Comment by PedroTiagoSimao** [comment]
Hi @fleiflei 

Yes, working ok now!

Thank you so much,
Pedro
