### ISSUE TITLE
Admin Ajax Crash when plugin is activated

### ISSUE THREAD

**Issue by dantahoua** [fleiflei/acf-admin-columns#2]
Hello! Great plugin. But sadly I have a strange problem with your plugin. Admin-ajax crash when the plugin is activated. The plugin works great in the admin, but seems something is odd somewhere. Here is what wordpress sent to me:

Si vous cherchez de l’aide pour ce problème, les informations suivantes pourraient vous être demandées :
WordPress version 5.3
Thème actuel : FoundationPress (version 2.10.4)
Extension actuelle : Admin Columns for ACF Fields (version 0.1)
PHP version 7.2.24

Détails de l’erreur
======================
Une erreur de type E_ERROR a été causée dans la ligne 478 du fichier /home/lesaintdev/sae.lesaintdev.com/wp-content/plugins/admin-columns-for-acf-fields/acf_admin_columns.php. Message d’erreur : Uncaught Error: Call to undefined function get_current_screen() in /home/lesaintdev/sae.lesaintdev.com/wp-content/plugins/admin-columns-for-acf-fields/acf_admin_columns.php:478
Stack trace:
#0 /home/lesaintdev/sae.lesaintdev.com/wp-content/plugins/admin-columns-for-acf-fields/acf_admin_columns.php(104): FleiACFAdminColumns->is_valid_admin_screen()
#1 /home/lesaintdev/sae.lesaintdev.com/wp-includes/class-wp-hook.php(288): FleiACFAdminColumns->action_prepare_columns(Object(WP_Term_Query))
#2 /home/lesaintdev/sae.lesaintdev.com/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#3 /home/lesaintdev/sae.lesaintdev.com/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home/lesaintdev/sae.lesaintdev.com/wp-includes/class-wp-term-query.php(317): do_action('pre_get_terms', Object(WP_Term_Query))
#5 /home/lesaintdev/sae.lesaintdev.com/wp-includes/class-wp-term-query.php(288): WP_Term_Query->get_terms()
#6 /home/lesaintdev/sae.lesaintdev.com/wp-includes/taxonomy.php(1179): WP_Term_Query->quer

**Comment by fleiflei** [comment]
Hey dantahoua, thanks for reporting this issue! I have updated the plugin so it is not triggered within ajax requests anymore.

Will update the Wordpress.org repo shortly so you can update through the WP backend. Until then please overwrite your local acf-admin-columns.php file with the updated version: https://github.com/fleiflei/acf-admin-columns/blob/master/acf_admin_columns.php

Let me know if you run into any other issues.

Thank you, 
Florian
