### ISSUE TITLE
Fatal error in Customizer

### ISSUE THREAD

**Issue by florianbrinkmann** [fleiflei/acf-admin-columns#3]
Hi,

first, thanks for the plugin! After activating it, opening the customizer throws the following error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function get_current_screen() in /wp-content/plugins/admin-columns-for-acf-fields/acf_admin_columns.php:478
```

I added the following lines to the start of the `is_valid_admin_screen()` method to fix that:

```
if (is_customize_preview()) {
	return false;
}
```

Would be great if you could add that or something similar to the code :)

Best,
Florian

**Comment by fleiflei** [comment]
Hey Florian,

thank you for pointing this out. I have fixed the plugin and pushed a new commit to Github as well as to the WP plugin directory (0.1.2). Please update.

Thanks and best regards,
Florian

**Comment by florianbrinkmann** [comment]
Hi Florian,

great, thanks!

Best,
Florian
