### ISSUE TITLE
non-object error

### ISSUE THREAD

**Issue by cschot** [fleiflei/acf-admin-columns#4]
Post Object field

( ! ) Notice: Trying to get property of non-object in (***)\wp-content\plugins\admin-columns-for-acf-fields\acf_admin_columns.php on line 320
--

**Comment by cschot** [comment]
Please link Pull Request: Null value causes error #5

**Comment by fleiflei** [comment]
Hey cschot,
thanks for pointing this out. I fixed this in https://github.com/fleiflei/acf-admin-columns/commit/b9a6158072d7fbad11dc32b9ba047ef00534822f.

Thank you and best regards,
Florian
