### ISSUE TITLE
Admin Column Content is "Array" -> Select Field

### ISSUE THREAD

**Issue by srueegger** [fleiflei/acf-admin-columns#6]
Hi!

Thank You very much for this Pkugin. Sorry for my bad English!

I have found a little Bug. When you create a Select Field and set the Return Value to "both" you have only "Array" in the Admin Column.

Maybe yo can check with "is_array()" the Type of the Return Var and output only the Label from Select field?

**Comment by srueegger** [comment]
I have write a Bugfix for the Problem, this Works in my Project.

This is my Code in the acf_admin_columns.php

```php
    case 'password':
                case 'select':
                    if(is_array($field_value)) {
                        $count_values = count($field_value);
                        $each_counter = 1;
                        $render_output = '';
                        foreach ($field_value as $fvalue) {
                            $render_output .= $fvalue['label'];
                            if($each_counter < $count_values) {
                                $render_output .= ', ';
                            }
                            $each_counter++;
                        }
                    } else {
                        $render_output = $field_value;
                    }
                    break;
                case 'checkbox':
```

**Comment by fleiflei** [comment]
Hey sruegger, 
thanks a lot for letting me know. I have fixed and pushed this (see https://github.com/fleiflei/acf-admin-columns/commit/e3d25ca4d2aadba0bddc044f025a9f1d018c6e47). Will update WP plugin repository shortly...

Thanks and best regards, 
Florian
