### ISSUE TITLE
Issue with images

### ISSUE THREAD

**Issue by playingcss** [fleiflei/acf-admin-columns#7]
ACF image field has 3 return formats:

![acf-image-format](https://user-images.githubusercontent.com/58046148/83532383-d8892c80-a4f6-11ea-9b87-3004ce59f36c.png)

This plugin addressing [only one type](https://github.com/fleiflei/acf-admin-columns/blob/master/acf_admin_columns.php#L331-L332).

I'm using "**Image URL**" as a "**Return Type**" and I get the following error:

> Warning: count(): Parameter must be an array or an object that implements Countable in C:\sites\dev-site\wp-content\plugins\admin-columns-for-acf-fields\acf_admin_columns.php on line 359

@fleiflei

**Comment by fleiflei** [comment]
Hey playingcss,
thanks for your message. Sorry, I was not able to reproduce this error yet...you are using one single image in ACF field type "image" and return it as URL? Can you post a screenshot of the fields complete ACF configuration?

Thanks and best regards, 
Florian

**Comment by fleiflei** [comment]
Hello @playingcss ,

the plugin has been improved a lot in the meantime...by now all return formats of images should be handled correctly...please check if it works for you with the latest version...

Best regards, 
Florian
