### ISSUE TITLE
Numerical Custom Field sorts Alphabetically

### ISSUE THREAD

**Issue by faddison** [fleiflei/acf-admin-columns#8]
I have a numerical column for post "Views"

I expect the ascending order to be:

(Title, Views)
PostA 5
PostB 10
PostC 15
PostD 20

The actual ascending order is:

(Title, Views)
PostB 10
PostC 15
PostD 20
PostA 5

**Comment by fleiflei** [comment]
Hello @faddison, 
this has been solved by now. Numeric fields are being sorted numerically since v0.2.0. Also I added a new filter "acf/admin_columns/sort_order_type" to overwrite the sort type for any column.
